name: ghstat
description: Calculate Lines of Code (LoC) written for a GitHub user
inputs:
  github-token:
    description: Token with read access to all analysed repos & gist write access
    required: true
  gist-id:
    description: ID of gist in which to store generated graphs
    required: false
    default: ''
  author:
    description: Git author name to search for in commit (default inferred from github-token)
    required: false
    default: ''
  user:
    description: GitHub username to analyse (default inferred from github-token)
    required: false
    default: ''
  repos-incl:
    description: GitHub repositories to include
    required: false
    default: ''
  repos-skip:
    description: Repositories to skip
    required: false
    default: ''
  lang-names:
    description: Language names for extensions (e.g. `conf:INI cuh:Cuda`)
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: setup
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: ghstat
      run: ${{ github.action_path }}/ghstat.sh
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_GIST_ID: ${{ inputs.gist-id }}
        AUTHOR: ${{ inputs.author }}
        GH_USER: ${{ inputs.user }}
        REPOS_INCL: ${{ inputs.repos-incl }}
        REPOS_SKIP: ${{ inputs.repos-skip }}
        LANG_NAMES: ${{ inputs.lang-names }}
